# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 3476f771a048a84ac793347027408731f9399c08bf94368d95133bd4f900bace81cf3cfc6c8223b0f043a69974651b6158af9911f179297e9075e0a2c999f4f0

test:
  secret_key_base: d013bac288e8d2a532a9d489a94459223028896cc217600a5e46e98843902232568526ceb1c1bf46c9c6571b2e5177f95441a688a3824b02ab8bf389ef8d3edb

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
